name: lms
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  animated_text_kit: ^4.2.2
  another_flushbar: ^1.12.30
  back_button_interceptor: ^7.0.3
  better_player: ^0.0.84
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_info_plus: ^10.1.2
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  connectivity_plus: ^5.0.2
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  go_router: ^14.1.3
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  open_file: ^3.5.3
  path_provider: ^2.1.4
  pdf: ^3.11.1
  pdf_image_renderer: ^0.7.0
  permission_handler: ^11.3.1
  readmore: ^3.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  short_navigation: ^1.0.0
  smooth_page_indicator: ^1.2.0+3
  youtube_explode_dart: ^2.3.0+1
  hydrated_bloc: ^9.1.5

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Fustat
      fonts:
        - asset: assets/fonts/NotoKufiArabic-VariableFont_wght.ttf
